[project]
name = "universal-med-ner"
version = "0.0.0"

dependencies = [
    "torch>=2.7",
    "torchvision",
    "torchaudio",
    "transformers",
    "datasets",
    "trl",
    "peft",
    "huggingface_hub",
    "sacremoses",
    "numpy",
    "pandas",
    "scipy",
    "wandb"
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }